---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.db.company.io
spec:
  group: db.company.io
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              engine:
                type: string
              version:
                type: string
              size:
                type: string

---

apiVersion: db.company.io/v1
kind: Database
metadata:
  name: database-crd
spec:
  engine: "mysql"
  version: "8.0"
  size: "5Gi"
